console.log("these are the constants");

GAME_WIDTH = 1000;
GAME_HEIGHT = 600;
PLAYER_SPEED = 100;
BG_HEIGHT = GAME_HEIGHT - 200;

//background
BACKGROUND_SCROLL = -30;
WIN_BG_SCALE_X = 3.5;
WIN_BG_SCALE_Y = 2.5;
WIN_BG_ALPHA = 0.8;

//fireworks
FIREWORK_SCALE = 5;
FIREWORK_POS_X_MULTIPLIER = 1000;
FIREWORK_POS_X_SUBTRACTOR = 100;
FIREWORK_POS_Y_MULTIPLIER = 200;
FIREWORK_POS_Y_SUBTRACTOR = 50;
FIREWORK_TIME = 800;
FIREWORK_RANDOM_NUMBER = 500;

//arena set-up
ARENA_POS_X = 500;
ARENA_POS_Y = 437.5;
ARENA_WIDTH = 300;
ARENA_HEIGHT = 300;
ARENA_SCALE_X = 2.5;
ARENA_SCALE_Y = .75;
ARENA_CENTER_X = 505;
ARENA_CENTER_Y = 435;

//rectangle set-up
RIGHT_RECTANGLE_X = ARENA_POS_X + 150;
RIGHT_RECTANGLE_Y = ARENA_POS_Y * 1.3;
LEFT_RECTANGLE_X = ARENA_POS_X - 150;
LEFT_RECTANGLE_Y = ARENA_POS_Y * 1.3;
RECTANGLE_SCALE_X = ARENA_SCALE_X / 1.7;
RECTANGLE_SCALE_Y = ARENA_SCALE_Y;

//calculatedDistance information
FOCUS_ONE_X = 864;
FOCUS_ONE_Y = 410;
FOCUS_TWO_X = 138;
FOCUS_TWO_Y = 410;
TOTAL_DISTANCE_FROM_FOCI = 765;

//player constants
PLAYER_ONE_INITIAL_POSITION_X = (ARENA_POS_X / 4) + (2 * ARENA_WIDTH) + 50;
PLAYER_ONE_INITIAL_POSITION_Y = (ARENA_POS_Y / 1.25) + (0.3 * ARENA_HEIGHT);
PLAYER_TWO_INITIAL_POSITION_X = (ARENA_POS_X / 4) + 100;
PLAYER_TWO_INITIAL_POSITION_Y = (ARENA_POS_Y / 1.25) + (0.3 * ARENA_HEIGHT);
PLAYER_SCALE = 3;
HIT_BOX_SCALE = 0.5;
SWITCH_DIRECTION = -1;
PLAYER_WINNING_POSITION_X = (ARENA_POS_X / 4) - 40;
PLAYER_WINNING_POSITION_Y = ARENA_POS_Y / 1.25;
PLAYER_WINNING_SCALE = 15;
PLAYER_LOSING_POSITION_X = 800;
PLAYER_LOSING_POSITION_Y = 210;

//rotation
STAGE_ROTATION = 0.0008;
RIGHT_RECTANGLE_HEIGHT_SCALER = 1.002;
LEFT_RECTANGLE_HEIGHT_SCALER = 1.00109;
RECTANGLE_SCALER_SCALER = .0000015;
// just added
RIGHT_RECTANGLE_WIDTH_SCALER = 1;
LEFT_RECTANGLE_WIDTH_SCALER = 1.0001;

FRAME_SPEED = 12;
HALF_FRAME_SPEED = 12;

//updatecounts
INITIATE_STUN_COUNT = 10;
COLLISION_STUN_COUNT = 190;
END_STUN_COUNT = 200;
TIMER_STARTS = 145

COLLISION_VELOCITY = 250;
KICKER_VELOCITY = COLLISION_VELOCITY;
KICKED_VELOCITY = COLLISION_VELOCITY * 2;

TIMER_COUNT = 90;
