console.log("these are the constants");

GAME_WIDTH = 1000;
GAME_HEIGHT = 600;
PLAYER_SPEED = 300;
BG_HEIGHT = GAME_HEIGHT - 200;
ARENA_POS_X = 125;
ARENA_POS_Y = 350;
ARENA_WIDTH = 300;
ARENA_HEIGHT = 300;
ARENA_SCALE_X = 2.5;
ARENA_SCALE_Y = .75;

PLAYER_ONE_INITIAL_POSITION_X = ARENA_POS_X + (2 * ARENA_WIDTH) + 100;
PLAYER_ONE_INITIAL_POSITION_Y = ARENA_POS_Y + (0.3 * ARENA_HEIGHT);
PLAYER_TWO_INITIAL_POSITION_X = ARENA_POS_X + 50;
PLAYER_TWO_INITIAL_POSITION_Y = ARENA_POS_Y + (0.3 * ARENA_HEIGHT);
PLAYER_WINNING_POSITION_X = ARENA_POS_X + ARENA_WIDTH + 50;
PLAYER_SCALE = 3;
HIT_BOX_SCALE = 0.5;
SWITCH_DIRECTION = -1;

FRAME_SPEED = 12;
HALF_FRAME_SPEED = 12;

INITIATE_STUN_COUNT = 10;
END_STUN_COUNT = 30;

OUT_OF_BOUNDS_X_LEFT = ARENA_POS_X - 34;
OUT_OF_BOUNDS_X_RIGHT = ARENA_POS_X + (2 * ARENA_WIDTH) + 150;
OUT_OF_BOUNDS_Y_BOTTOM = ARENA_POS_Y - 50;
OUT_OF_BOUNDS_Y_TOP = ARENA_POS_Y + (0.63 * ARENA_HEIGHT);

COLLISION_VELOCITY = 300;

TIMER_COUNT = 120;
