console.log("these are the constants");

GAME_WIDTH = 1000;
GAME_HEIGHT = 600;
PLAYER_SPEED = 300;
BG_HEIGHT = GAME_HEIGHT - 200;

//background
BACKGROUND_SCROLL = -30;
WIN_BG_SCALE_X = 3.5;
WIN_BG_SCALE_Y = 2.5;
WIN_BG_ALPHA = 0.8;

//fireworks
FIREWORK_SCALE = 5;
FIREWORK_POS_X_MULTIPLIER = 1000;
FIREWORK_POS_X_SUBTRACTOR = 100;
FIREWORK_POS_Y_MULTIPLIER = 200;
FIREWORK_POS_Y_SUBTRACTOR = 50;
FIREWORK_TIME = 800;
FIREWORK_RANDOM_NUMBER = 500;

//arena set-up
ARENA_POS_X = 500;
ARENA_POS_Y = 437.5;
ARENA_WIDTH = 300;
ARENA_HEIGHT = 300;
ARENA_SCALE_X = 2.5;
ARENA_SCALE_Y = .75;
ARENA_CENTER_X = 505;
ARENA_CENTER_Y = 435;

//rectangle set-up
RIGHT_RECTANGLE_X = ARENA_POS_X + 150;
RIGHT_RECTANGLE_Y = ARENA_POS_Y * 1.3;
LEFT_RECTANGLE_X = ARENA_POS_X - 150;
LEFT_RECTANGLE_Y = ARENA_POS_Y * 1.3;
RECTANGLE_SCALE_X = ARENA_SCALE_X / 1.7;
RECTANGLE_SCALE_Y = ARENA_SCALE_Y;
//RECTANGLE_SCALER = 1;

//calculatedDistance information
// FOCUS_ONE_INITIAL = {x:872, y:435};
// FOCUS_TWO_INITIAL = {x:138, y:435};
FOCUS_ONE_X = 872;
FOCUS_ONE_Y = 435;
FOCUS_TWO_X = 138;
FOCUS_TWO_Y = 435;
TOTAL_DISTANCE_FROM_FOCI = 770;

//player constants
PLAYER_ONE_INITIAL_POSITION_X = (ARENA_POS_X / 4) + (2 * ARENA_WIDTH) + 100;
PLAYER_ONE_INITIAL_POSITION_Y = (ARENA_POS_Y / 1.25) + (0.3 * ARENA_HEIGHT);
PLAYER_TWO_INITIAL_POSITION_X = (ARENA_POS_X / 4) + 50;
PLAYER_TWO_INITIAL_POSITION_Y = (ARENA_POS_Y / 1.25) + (0.3 * ARENA_HEIGHT);
PLAYER_SCALE = 3;
HIT_BOX_SCALE = 0.5;
SWITCH_DIRECTION = -1;
PLAYER_WINNING_POSITION_X = (ARENA_POS_X / 4) - 100;
PLAYER_WINNING_POSITION_Y = ARENA_POS_Y / 1.25;
PLAYER_WINNING_SCALE = 15;
PLAYER_LOSING_POSITION_X = 800;
PLAYER_LOSING_POSITION_Y = 210;

//rotation
STAGE_ROTATION = 0.0008;
RIGHT_RECTANGLE_HEIGHT_SCALER = 1.003;
LEFT_RECTANGLE_HEIGHT_SCALER = 1.0018;
RECTANGLE_SCALER_SCALER = .0000006;

FRAME_SPEED = 12;
HALF_FRAME_SPEED = 12;

INITIATE_STUN_COUNT = 10;
END_STUN_COUNT = 30;

OUT_OF_BOUNDS_X_LEFT = (ARENA_POS_X / 4) - 34;
OUT_OF_BOUNDS_X_RIGHT = (ARENA_POS_X / 4) + (2 * ARENA_WIDTH) + 150;
OUT_OF_BOUNDS_Y_BOTTOM = (ARENA_POS_Y / 1.25) - 50;
OUT_OF_BOUNDS_Y_TOP = (ARENA_POS_Y / 1.25) + (0.63 * ARENA_HEIGHT);

COLLISION_VELOCITY = 300;
KICKER_VELOCITY = COLLISION_VELOCITY * 2;
KICKED_VELOCITY = COLLISION_VELOCITY * 3;

TIMER_COUNT = 65;
